baseURL = "https://www.alexdarbyshire.com"
languageCode = "en-au"
title = "Alex Darbyshire"
theme = 'terminal'

# Required for Chroma and custom syntax highlighting
[markup.highlight]
noClasses = false

enableRobotsTXT = true

# Define pagination settings
[pagination]
  pagerSize = 7 

# not pluralize title pages by default
pluralizelisttitles = false


#Allow direct use of html and script in markdown
[markup.goldmark.renderer]
  unsafe = true

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[services.googleAnalytics]
    id = 'G-C05H5792C7'

[params]
  copyright = "Copyright © 2025, Alex Darbyshire"
  dateFormat = "January 2, 2006"
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true 
  autoCover = true
  showLastUpdated = false
  readingTime = true
  Toc = true 
  # TocTitle = "Table of Contents"  # Uncomment to customize

[params.logo]
  logoText = "Alex Darbyshire"
  logoHomeLink = "/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Alex Darbyshire"
    [languages.en.params]
      subtitle = ""  # Add your subtitle here if desired
      owner = "Alex Darbyshire"
      keywords = ""  # Add your keywords here
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

[[menu.main]]
    name       = "Posts"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Github"
    identifier = "menu.github"
    url        = "https://github.com/alexdarbyshire/alexdarbyshire.com"
    weight     = 3

