version: "3"
services:
  nginx-hugo:
    image: homelab/alexdarbyshire-site:latest
    container_name: nginx-hugo
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_alexdarbyshire
    restart: always
    environment:
            - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN} #Docker secrets would be preferable, cloudflared image isn't setup to read token from a file. Can be done using a custom Dockerfile. See https://gist.github.com/j0sh/b1971bfbbffeb92709cf096fb788f70c
    command: tunnel --no-autoupdate run --token "$CLOUDFLARE_TUNNEL_TOKEN"    
