apiVersion: v1
kind: Pod 
metadata:
  labels:
    app: registry
  name: registry
spec:
  containers:
  - image: registry:2
    name: registry
    volumeMounts:
    - name: volv
      mountPath: /var/lib/registry
    ports:
     - containerPort: 5000
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: local-path-pvc

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: registry
  type: LoadBalancer
